// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using Microsoft.AspNetCore.Mvc;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Project1.Models;


public partial class UserLogin
{
    public int Id { get; set; }

    [NotMapped]
    [BindProperty]
    public string EncryptedId { get; set; }

    [Display(Name = "Email")]
    [Required]
    public string EmailAddress { get; set; }

    [DataType(DataType.Text)]
    [Required]
    public string Pin { get; set; }
}